### ISSUE TITLE
Complete Level 2 Development Hit List

### ISSUE THREAD

**Issue by skuhlmann** [HausDAO/farcastle-frames#36]
![](https://i.giphy.com/media/v1.Y2lkPTc5MGI3NjExZjUwMXg2cTV4am91MHp1dHBjc3B2dTh3amt1MnZqOW1sbTdlNGhjNyZlcD12MV9pbnRlcm5hbF9naWZfYnlfaWQmY3Q9Zw/gMqTCnnzUpHbi/giphy.gif)

**DAO Home**
- [x] change active proposal count to all proposal
- [x] Active Proposals intent if proposalCount if more than 0
		- link to proposals route + query there and display latest or none
- [x] intent View all link to admin
- [x] members and safes intents

To Do
- how will we handle stale active proposals
- proposals route that checks and sends to another route?
   - look into frog middleware

**Proposal**
- [x] execute intent if in that state
- [x] intent to proposal details

**Vote**
- [x] add status
- [x] hide tx intent if not voting
- [x] add execute if needs processing
- [x] maintain proposal pagination on back button

**success**
- [x] rework usage

**Add networks**
- [x] all supported

**Update routing**
- [x] match daohaus v3 app

```
 "eip155:1" - mainnet
"eip155:10" - op
"eip155:100" - gnosis chain
"eip155:8453" - base
"eip155:42161" - arb
137 - polygon
```

**Comment by skuhlmann** [comment]
broken
- no vote
- no proposal states
- proposal details link went to dao overview

**Comment by earth2travis** [comment]
On the DAO Overview frame update the `Members` intent to go to the Members view of the DAO. Right now it is pointing to Proposal Details

http://localhost:5173/molochv3/0xa/0x2a244bb4ccd4eb0897cf61e0c61963e1e1d161e3

**Comment by earth2travis** [comment]
![Image](https://github.com/user-attachments/assets/2282e7db-2aa6-4fdb-8917-b45c8a922558)

Let's shorten the description on the proposals

**Comment by earth2travis** [comment]
The proposals details intent does not seem to be pointing to the proposal displayed in the frame. When viewing proposal 2:

![Image](https://github.com/user-attachments/assets/f81a32a3-f366-4359-a12e-0e05ba75f448)

The Details intent opens proposal 3:

https://admin.daohaus.club/#/molochv3/0xa/0x2a244bb4ccd4eb0897cf61e0c61963e1e1d161e3/proposal/3

**Comment by earth2travis** [comment]
The proposals details intent does not seem to be pointing to the proposal displayed in the frame. When viewing proposal 4:

![Image](https://github.com/user-attachments/assets/971c46b7-75e0-484d-bcb9-af1e5a471c79)

The Details intent opens members:

https://admin.daohaus.club/#/molochv3/0xa/0x2a244bb4ccd4eb0897cf61e0c61963e1e1d161e3/members

**Comment by earth2travis** [comment]
On the execution frame

![Image](https://github.com/user-attachments/assets/e1f5e00b-a979-4ce8-8ee1-10621b79b0ed)

The details intent currently points to the Members view of DAOhaus Admin

**Comment by earth2travis** [comment]
The success view on the Execute frame needs to be updated to point to `execute: 'Proposal Executed',`

It currently shows:

![Image](https://github.com/user-attachments/assets/13d16e8b-ea70-4852-9bdf-37d94676d7b7)

**Comment by earth2travis** [comment]
On this proposals view:

![Image](https://github.com/user-attachments/assets/2ef89ae3-0277-495f-8820-0299db48c93a)

There is one proposal that needs to be executed and one that failed. Ideally if there is one that needs execution the intent would go to the proposal. If that is too complicated NBD

However, the link from the proposals intent is pointing to: https://admin.daohaus.club/#/molochV3/0xa/0x2a244bb4ccd4eb0897cf61e0c61963e1e1d161e3/proposal/2

It should be pointing to: https://admin.daohaus.club/#/molochv3/0xa/0x2a244bb4ccd4eb0897cf61e0c61963e1e1d161e3/proposals

**Comment by earth2travis** [comment]
Do not know if it matters but:

## Frames

- http://localhost:5173/molochv3/:chainid/:daoid/proposals/:proposalids
- http://localhost:5173/molochv3/:chainid/:daoid/proposals/:proposalids/vote (this one is singular on DH Admin)

## v3

https://admin.daohaus.club/#/molochv3/0xa/0x2a244bb4ccd4eb0897cf61e0c61963e1e1d161e3/proposals
https://admin.daohaus.club/#/molochV3/0xa/0x2a244bb4ccd4eb0897cf61e0c61963e1e1d161e3/proposal/6
