### ISSUE TITLE
Complete Level 2 Design Hit List

### ISSUE THREAD

**Issue by skuhlmann** [HausDAO/farcastle-frames#37]
![](https://i.giphy.com/media/v1.Y2lkPTc5MGI3NjExY3NsZ3pyMmRsenFybTByMG1jMXVqY2QybjY0azMwNHYzZjloYmY0dCZlcD12MV9pbnRlcm5hbF9naWZfYnlfaWQmY3Q9Zw/lE2Npt5sfCwuY/giphy.gif)

- [x] Proposal
- [x] Vote
- [x] Success
- [x] Error

**Comment by earth2travis** [comment]
Relates to: https://github.com/orgs/HausDAO/projects/29/views/2?pane=issue&itemId=85153982&issue=HausDAO%7Cfarcastle%7C49

**Comment by earth2travis** [comment]
https://github.com/HausDAO/farcastle-frames/pull/43

**Comment by earth2travis** [comment]
Final v1 design tweak made in: https://github.com/HausDAO/farcastle-frames/pull/53
