### ISSUE TITLE
Create a Staging/Testing Deployment for Frames

### ISSUE THREAD

**Issue by skuhlmann** [HausDAO/farcastle-frames#9]
- [x] change the base branch to develop.  
- [x] create staging deployment in cloudflare

## git flow 
1. pull feature branches from `develop` 
2. pr feature branch back into develop. 
3. pr develop into main when ready for production deployment.

**Comment by earth2travis** [comment]
![Image](https://github.com/user-attachments/assets/d2be7c54-a72d-4ff5-91d9-1a11cd5b3e6f)

Closing

**Comment by earth2travis** [comment]
Closing
